//! Assemble `ast::Module` values from DB rows + policy, then render them via
//! `newm2_parser::format_types_module` (guaranteeing parser-valid output).

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};

use newm2_parser::ast::{Decl, Expr, RecordField};
use newm2_parser::format_types_module;
use rusqlite::Connection;

use crate::build;
use crate::db;
use crate::policy::{self, ResolveCtx};

pub struct GenResult {
    pub module_name: String,
    pub text: String,
    pub warnings: Vec<String>,
}

/// Provenance banner prepended to every generated module (a comment is
/// whitespace to the parser, so it does not affect parsing or the pack).
const PROVENANCE: &str =
    "(* Generated by newm2-winapi-gen from windows_api.db — do not edit by hand. *)\n";

/// Render the shared `WIN32` base module (the Win32 typedefs + GUID record).
pub fn generate_win32_base() -> String {
    let mut decls: Vec<Decl> = Vec::new();

    // GUID first (a real record), then the scalar/pointer typedefs.
    decls.push(build::type_decl(
        "GUID",
        build::record(vec![
            build::record_field("Data1", build::named("DWORD")),
            build::record_field("Data2", build::named("WORD")),
            build::record_field("Data3", build::named("WORD")),
            build::record_field(
                "Data4",
                build::array(build::subrange(build::int_expr(0), build::int_expr(7)), build::named("BYTE")),
            ),
        ]),
    ));

    for (name, def) in policy::win32_base_defs() {
        decls.push(build::type_decl(name, def.to_type_expr()));
    }

    let module = build::module("WIN32", vec![], decls);
    format!("{PROVENANCE}{}", format_types_module(&module).text)
}

/// The M2 module name for a namespace: strip the `Windows.Win32.` prefix and
/// flatten the remaining dotted path with `_`, so names are unique across all
/// namespaces (a bare last segment collides, e.g. several `.Display`).
/// `Windows.Win32.System.Console` -> `System_Console`, `…Foundation` ->
/// `Foundation`.
pub fn module_name_for(ns: &str) -> String {
    ns.strip_prefix("Windows.Win32.").unwrap_or(ns).replace('.', "_")
}

/// Build the cross-namespace index over all namespaces being generated: which
/// qualified types are structs (emitted as types) vs enums (emitted as CONSTs,
/// so referenced by backing scalar).
pub fn build_cross_index(
    conn: &Connection,
    namespaces: &[String],
) -> rusqlite::Result<policy::CrossIndex> {
    let win32_owned = policy::win32_names();
    let mut index = policy::CrossIndex::default();
    for ns in namespaces {
        let module = module_name_for(ns);
        for t in db::load_types(conn, ns)? {
            if t.kind == "struct" && !win32_owned.contains(&t.type_name) {
                index
                    .structs
                    .insert(format!("{ns}.{}", t.type_name), (module.clone(), t.type_name.clone()));
            }
        }
        let mut seen = HashSet::new();
        for em in db::load_enum_members(conn, ns)? {
            if seen.insert(em.enum_name.clone()) {
                index.enums.insert(
                    format!("{ns}.{}", em.enum_name),
                    policy::enum_backing_builtin(&em.underlying_type),
                );
            }
        }
    }
    Ok(index)
}

/// The cross-namespace interface index: every interface (with an IID) keyed by
/// qualified name, used to compute absolute vtable ordinals (`@N`) and to
/// resolve a base interface to its generated module + simple name.
pub struct InterfaceIndex {
    by_qname: HashMap<String, db::IfaceIndexRow>,
}

impl InterfaceIndex {
    pub fn load(conn: &Connection) -> rusqlite::Result<Self> {
        let mut by_qname = HashMap::new();
        for row in db::load_interface_index(conn)? {
            by_qname.insert(row.qualified_name.clone(), row);
        }
        Ok(InterfaceIndex { by_qname })
    }

    /// Total vtable size of the interfaces *above* `qname` — i.e. the absolute
    /// ordinal at which `qname`'s own slot 0 lands. Walks `base_qualified_name`
    /// to the root, guarding against cycles / dangling bases (returns the count
    /// accumulated so far if the chain is broken).
    pub fn base_offset(&self, qname: &str) -> i64 {
        let mut offset = 0i64;
        let mut seen: std::collections::HashSet<&str> = std::collections::HashSet::new();
        let mut cur = self.by_qname.get(qname).and_then(|r| r.base_qualified_name.as_deref());
        while let Some(base_q) = cur {
            if !seen.insert(base_q) {
                break; // cycle guard
            }
            match self.by_qname.get(base_q) {
                Some(base) => {
                    offset += base.own_method_count;
                    cur = base.base_qualified_name.as_deref();
                }
                None => break, // base not in the index (missing) — stop
            }
        }
        offset
    }

    pub fn get(&self, qname: &str) -> Option<&db::IfaceIndexRow> {
        self.by_qname.get(qname)
    }
}

pub fn generate_namespace(
    conn: &Connection,
    ns: &str,
    index: &policy::CrossIndex,
) -> rusqlite::Result<GenResult> {
    generate_namespace_with_ifaces(conn, ns, index, None)
}

/// Like [`generate_namespace`], but also emits COM `INTERFACE` declarations when
/// an [`InterfaceIndex`] is supplied (for absolute-ordinal + base resolution).
pub fn generate_namespace_with_ifaces(
    conn: &Connection,
    ns: &str,
    index: &policy::CrossIndex,
    iface_index: Option<&InterfaceIndex>,
) -> rusqlite::Result<GenResult> {
    let types = db::load_types(conn, ns)?;
    let constants = db::load_constants(conn, ns)?;
    let enum_members = db::load_enum_members(conn, ns)?;
    let struct_fields = db::load_struct_fields(conn, ns)?;

    let module_name = module_name_for(ns);
    let mut warnings: Vec<String> = Vec::new();
    let win32_owned = policy::win32_names();

    // --- classify types ---------------------------------------------------
    let mut abi_of: HashMap<String, Option<String>> = HashMap::new();
    let mut struct_names: BTreeSet<String> = BTreeSet::new();
    // Struct total size in BYTES (from winmd size_bits), to recover a trailing
    // fixed-array field's length (span = struct_size - field_offset).
    let mut struct_size_bytes: HashMap<String, i64> = HashMap::new();
    for t in &types {
        if t.kind == "struct" {
            abi_of.insert(t.type_name.clone(), t.abi_kind.clone());
            if let Some(bits) = t.size_bits {
                struct_size_bytes.insert(t.type_name.clone(), bits / 8);
            }
            if !win32_owned.contains(&t.type_name) {
                struct_names.insert(t.type_name.clone());
            }
        }
    }

    // fields grouped by struct
    let mut fields_of: BTreeMap<String, Vec<&db::StructFieldRow>> = BTreeMap::new();
    for f in &struct_fields {
        fields_of.entry(f.struct_name.clone()).or_default().push(f);
    }

    // enum backing builtin per enum
    let mut enum_backing: HashMap<String, String> = HashMap::new();
    let mut enum_order: Vec<String> = Vec::new();
    for em in &enum_members {
        if !enum_backing.contains_key(&em.enum_name) {
            enum_backing.insert(em.enum_name.clone(), policy::enum_backing_builtin(&em.underlying_type));
            enum_order.push(em.enum_name.clone());
        }
    }

    let ctx = ResolveCtx {
        local_structs: struct_names.iter().cloned().collect::<HashSet<_>>(),
        enum_backing: enum_backing.clone(),
    };

    // --- CONST section ----------------------------------------------------
    let mut decls: Vec<Decl> = Vec::new();
    let mut const_names: HashSet<String> = HashSet::new();

    for c in &constants {
        match const_value_expr(c) {
            Some(value) => {
                if const_names.insert(c.name.clone()) {
                    decls.push(build::const_decl(&c.name, value));
                } else {
                    warnings.push(format!("duplicate const name '{}' skipped", c.name));
                }
            }
            None => warnings.push(format!("const '{}' kind '{}' has no value (skipped)", c.name, c.value_kind)),
        }
    }

    // enum members -> CONST integers (first pass: every enum lowers to consts)
    for em in &enum_members {
        let value = if em.signedness == "signed" {
            if em.value_i64 < 0 {
                build::neg_int_expr((-(em.value_i64)) as u64)
            } else {
                build::int_expr(em.value_i64 as u64)
            }
        } else {
            build::int_expr(em.value_u64 as u64)
        };
        if const_names.insert(em.member_name.clone()) {
            decls.push(build::const_decl(&em.member_name, value));
        } else {
            warnings.push(format!("duplicate enum member '{}' skipped", em.member_name));
        }
    }

    // --- TYPE section -----------------------------------------------------
    let mut win32_imports: BTreeSet<String> = BTreeSet::new();
    let mut cross_imports: BTreeSet<String> = BTreeSet::new();
    for name in &struct_names {
        let is_union = abi_of.get(name).and_then(|a| a.clone()).as_deref() == Some("explicit-layout");
        let fields = fields_of.get(name);
        match fields {
            Some(fields) if !is_union && !fields.is_empty() => {
                let mut rec_fields: Vec<RecordField> = Vec::new();
                let mut seen_fields: BTreeSet<String> = BTreeSet::new();
                for (i, f) in fields.iter().enumerate() {
                    let fname = sanitize_ident(&f.field_name);
                    // The metadata occasionally lists a field twice (e.g.
                    // MINIDUMP_THREAD_CALLBACK.StackEnd); a record may not
                    // declare the same field name twice, so keep the first.
                    if !seen_fields.insert(fname.clone()) {
                        warnings.push(format!("struct '{name}': duplicate field '{fname}' dropped"));
                        continue;
                    }
                    // A fixed-array struct field arrives as `Elem[]` (the winmd
                    // ArrayShape length was dropped). Recover the count from the
                    // field's byte span — next field's offset, or the struct size
                    // for a trailing field — so the record stays the correct size
                    // (was wrongly ADDRESS, under-sizing the struct).
                    let elem = f.type_name.trim_end();
                    let m2 = if let Some(elem) = elem.strip_suffix("[]") {
                        let next_off = fields.get(i + 1).and_then(|nf| nf.byte_offset);
                        let span = match (f.byte_offset, next_off) {
                            (Some(o), Some(n)) => Some(n - o),
                            (Some(o), None) => struct_size_bytes.get(name).map(|s| s - o),
                            _ => None,
                        };
                        match span {
                            Some(sp) if sp > 0 => policy::resolve_field_array(
                                elem.trim_end(),
                                sp,
                                &ctx,
                                index,
                                &module_name,
                                &mut warnings,
                            ),
                            _ => policy::resolve(&f.type_name, &ctx, index, &module_name, &mut warnings),
                        }
                    } else {
                        policy::resolve(&f.type_name, &ctx, index, &module_name, &mut warnings)
                    };
                    m2.collect_imports(&mut win32_imports, &mut cross_imports);
                    rec_fields.push(build::record_field(&fname, m2.to_type_expr()));
                }
                decls.push(build::type_decl(name, build::record(rec_fields)));
            }
            _ => {
                if is_union {
                    warnings.push(format!("union '{name}' emitted opaque (explicit layout)"));
                } else {
                    warnings.push(format!("struct '{name}' has no captured fields — emitted opaque"));
                }
                decls.push(build::opaque_type_decl(name));
            }
        }
    }

    // --- PROCEDURE section ------------------------------------------------
    // Pointer params keep their pointer type (C ABI); winmd does not record
    // in/out direction, so we emit value params of POINTER TO T rather than
    // VAR. A/W variants are emitted verbatim (no dedup) in this pass.
    let functions = db::load_functions(conn, ns)?;
    for f in &functions {
        let param_rows = db::load_params(conn, f.function_id)?;
        let mut params = Vec::new();
        for (i, p) in param_rows.iter().enumerate() {
            let m2 = match p.type_name.as_deref() {
                None | Some("void") => policy::M2Ref::Address,
                Some(s) => policy::resolve(s, &ctx, index, &module_name, &mut warnings),
            };
            m2.collect_imports(&mut win32_imports, &mut cross_imports);
            let pname = p
                .name
                .as_deref()
                .filter(|s| !s.is_empty())
                .map(sanitize_ident)
                .unwrap_or_else(|| format!("arg{i}"));
            params.push(build::value_param(&pname, m2.to_type_expr()));
        }
        let return_ty = match f.return_type.as_deref() {
            None | Some("void") => None,
            Some(s) => {
                let m2 = policy::resolve(s, &ctx, index, &module_name, &mut warnings);
                m2.collect_imports(&mut win32_imports, &mut cross_imports);
                Some(m2.to_type_expr())
            }
        };
        let linkage = match f.dll_name.as_deref() {
            Some(dll) if !dll.is_empty() => {
                let link = f.import_name.as_deref().filter(|s| !s.is_empty()).unwrap_or(f.name.as_str());
                Some(build::external_linkage(link, dll))
            }
            _ => {
                warnings.push(format!("function '{}' has no DLL — emitted unbound", f.name));
                None
            }
        };
        decls.push(build::proc_decl(&f.name, linkage, params, return_ty));
    }

    // --- INTERFACE section -------------------------------------------------
    // COM interfaces are vtable-only abstract classes. Param/return types use
    // the raw-ABI mapping (every pointer -> ADDRESS, by-value scalar -> its M2
    // scalar). Each method carries an absolute vtable ordinal `<* @N *>` the M2
    // compiler machine-checks against its own INHERIT-chain computation.
    if let Some(iface_idx) = iface_index {
        for iface in db::load_interfaces(conn, ns)? {
            // INHERIT clause: resolve the base interface to (module, simple).
            let inherit = match iface.base_qualified_name.as_deref() {
                None => None,
                Some(base_q) => match iface_idx.get(base_q) {
                    Some(base_row) => {
                        let base_module = module_name_for(&base_row.namespace);
                        if base_module == module_name {
                            Some(build::qual_name(vec![base_row.name.clone()]))
                        } else {
                            cross_imports.insert(base_module.clone());
                            Some(build::qual_name(vec![base_module, base_row.name.clone()]))
                        }
                    }
                    None => {
                        warnings.push(format!(
                            "interface '{}' base '{base_q}' not found in index — INHERIT omitted",
                            iface.name
                        ));
                        None
                    }
                },
            };

            // Absolute ordinal where this interface's own slot 0 lands.
            let base_offset = iface_idx.base_offset(&iface.qualified_name);

            let mut members = Vec::new();
            for m in &iface.methods {
                let mut params = Vec::new();
                for (i, p) in m.params.iter().enumerate() {
                    let m2 = match p.type_name.as_deref() {
                        None => policy::M2Ref::Address,
                        Some(s) => policy::resolve_iface_type(s, &ctx, index, &module_name, &mut warnings),
                    };
                    m2.collect_imports(&mut win32_imports, &mut cross_imports);
                    let pname = p
                        .name
                        .as_deref()
                        .filter(|s| !s.is_empty())
                        .map(sanitize_ident)
                        .unwrap_or_else(|| format!("arg{i}"));
                    params.push(build::value_param(&pname, m2.to_type_expr()));
                }
                let return_ty = match m.return_type.as_deref() {
                    None | Some("void") => None,
                    Some(s) => {
                        let m2 = policy::resolve_iface_type(s, &ctx, index, &module_name, &mut warnings);
                        m2.collect_imports(&mut win32_imports, &mut cross_imports);
                        Some(m2.to_type_expr())
                    }
                };
                let ordinal = (base_offset + m.slot_index) as usize;
                members.push(build::interface_method(&m.name, params, return_ty, ordinal));
            }

            decls.push(build::interface_decl(
                &iface.name,
                iface.iid.as_deref(),
                inherit,
                members,
            ));
        }
    }

    // --- imports ----------------------------------------------------------
    let mut imports = Vec::new();
    if !win32_imports.is_empty() {
        imports.push(build::import_from("WIN32", win32_imports.into_iter().collect()));
    }
    cross_imports.remove(&module_name); // never import self
    if !cross_imports.is_empty() {
        imports.push(build::import_plain(cross_imports.into_iter().collect()));
    }

    // win32metadata sometimes defines a constant and a struct (or two structs)
    // under one name (HTTP_VERSION, AE_ACLMOD, VK_F). Modula-2 has a single
    // per-module namespace, so resolve collisions: a type/procedure is kept
    // (it is referenced structurally) and a colliding constant is dropped;
    // any remaining exact duplicate keeps its first occurrence.
    let type_proc_names: BTreeSet<String> = decls
        .iter()
        .filter_map(|d| match d {
            Decl::Type(t) => Some(t.name.clone()),
            Decl::Procedure(p) => Some(p.name.clone()),
            _ => None,
        })
        .collect();
    decls.retain(|d| match d {
        Decl::Const(c) if type_proc_names.contains(&c.name) => {
            warnings.push(format!(
                "constant '{}' dropped (collides with a type/procedure of the same name)",
                c.name
            ));
            false
        }
        _ => true,
    });
    let mut seen_decls: BTreeSet<String> = BTreeSet::new();
    decls.retain(|d| {
        let name = match d {
            Decl::Const(c) => &c.name,
            Decl::Type(t) => &t.name,
            Decl::Procedure(p) => &p.name,
            _ => return true,
        };
        if seen_decls.insert(name.clone()) {
            true
        } else {
            warnings.push(format!("duplicate declaration '{name}' dropped"));
            false
        }
    });

    let module = build::module(&module_name, imports, decls);
    let text = format!("{PROVENANCE}{}", format_types_module(&module).text);

    Ok(GenResult { module_name, text, warnings })
}

fn const_value_expr(c: &db::ConstRow) -> Option<Expr> {
    match c.value_kind.as_str() {
        "int" => {
            let v = c.value_i64?;
            Some(if v < 0 { build::neg_int_expr((-v) as u64) } else { build::int_expr(v as u64) })
        }
        "uint" | "bool" | "char" => Some(build::int_expr(c.value_u64? as u64)),
        "float" => Some(build::real_expr(c.value_f64?)),
        "string" => {
            let s = c.value_text.as_deref()?;
            // M2 string literals have no escapes: a control char can't appear,
            // and a value containing both quote kinds can't be delimited.
            if s.bytes().any(|b| b < 0x20) || (s.contains('"') && s.contains('\'')) {
                return None;
            }
            Some(build::string_expr(s))
        }
        _ => None, // guid / typed / null — value deferred
    }
}

/// Escape M2 reserved words appearing as field names.
fn sanitize_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "TYPE", "TO", "END", "SET", "IN", "MOD", "VAR", "DIV", "OR", "AND", "NOT", "DO", "OF", "IF",
        "CASE", "FOR", "WITH", "ARRAY", "RECORD", "CONST", "BEGIN", "LOOP", "THEN", "ELSE", "FROM",
    ];
    if RESERVED.contains(&name.to_uppercase().as_str()) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}
